export let BASE_API="http://localhost:8080/api/v1"
export const SOCIAL_SIGIN_SUCCESS ="/socialLogin/success"
export const SOCIAL_SIGIN_FAILED ="/socialLogin/failed"
export const SIGIN="/login"
export const SIGNUP="/registration"